#pragma once
#include <cstdint>

using OrderId  = std::uint64_t;
using Price    = std::uint64_t;
using Quantity = std::uint32_t;
using ClientId = std::uint64_t;
using TickerId = std::uint32_t;

enum class Side { BUY, SELL };
enum class OrderType { GoodTillCancel, FillAndKill };
enum class ClientRequestType { NEW, CANCEL, MODIFY };
enum class ResponseType { ACCEPTED, FILLED, CANCELED, MODIFIED };
enum class UpdateType { ADD, CANCEL, MODIFY, TRADE };             

struct MEClientRequest {

    ClientRequestType action_; 
    ClientId client_id_;
    TickerId ticker_id_;      //Stock name
    OrderId client_order_id_; // The ID generated by AlphaTrader
    OrderType type_;
    Side side_;
    Price price_;
    Quantity qty_;
};

// QUEUE 2: Outbound Private (Engine -> Gateway -> AlphaTrader)
struct MEClientResponse {
    ClientId client_id_;
    TickerId ticker_id_;
    OrderId client_order_id_; // So AlphaTrader knows which order we mean
    OrderId market_order_id_; // The Exchange's official ID for this order
    
    ResponseType status_;
    Quantity executed_qty_;
    Price execution_price_;
    Quantity leaves_qty_;      // How much quantity is still resting
};

// QUEUE 3: Outbound Public (Engine -> Publisher -> ITCH Feed)
struct MEMarketUpdate {
    TickerId ticker_id_;
    OrderId market_order_id_; // The public ITCH Reference Number
    UpdateType type_;
    Side side_;
    Price price_;
    Quantity qty_;
};

